# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\lab5\main_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.csv_page = QtWidgets.QWidget()
        self.csv_page.setObjectName("csv_page")
        self.btn_csv = QtWidgets.QPushButton(self.csv_page)
        self.btn_csv.setEnabled(True)
        self.btn_csv.setGeometry(QtCore.QRect(330, 240, 161, 91))
        self.btn_csv.setObjectName("btn_csv")
        self.stackedWidget.addWidget(self.csv_page)
        self.image_page = QtWidgets.QWidget()
        self.image_page.setObjectName("image_page")
        self.label = QtWidgets.QLabel(self.image_page)
        self.label.setGeometry(QtCore.QRect(60, 20, 701, 371))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.setScaledContents(True)
        self.btn_csv_2 = QtWidgets.QPushButton(self.image_page)
        self.btn_csv_2.setGeometry(QtCore.QRect(270, 542, 263, 41))
        self.btn_csv_2.setObjectName("btn_csv_2")
        self.btn_left = QtWidgets.QPushButton(self.image_page)
        self.btn_left.setGeometry(QtCore.QRect(90, 440, 171, 71))
        self.btn_left.setObjectName("btn_left")
        self.btn_right = QtWidgets.QPushButton(self.image_page)
        self.btn_right.setGeometry(QtCore.QRect(540, 440, 171, 71))
        self.btn_right.setObjectName("btn_right")
        self.stackedWidget.addWidget(self.image_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_csv.setText(_translate("MainWindow", "Select csv file"))
        self.btn_csv_2.setText(_translate("MainWindow", "Select csv"))
        self.btn_left.setText(_translate("MainWindow", "<----"))
        self.btn_right.setText(_translate("MainWindow", "---->"))
